server:
  port: 8090

spring:
  application:
    name: yunxingcloud-gateway

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.yunxingcloud: DEBUG
    org.springframework.cloud.gateway: DEBUG
