spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

logging:
  pattern:
    console: "%d{HH:mm:ss} [%X{requestId}] %-5level %logger{20} - %msg%n"
  level:
    root: WARN
    com.yunxingcloud: INFO
    org.springframework.security: INFO

management:
  health:
    mail:
      enabled: false