CREATE INDEX idx_oper_log_time ON sys_oper_log(oper_time);
CREATE INDEX idx_oper_log_type ON sys_oper_log(business_type);
CREATE INDEX idx_oper_log_user ON sys_oper_log(oper_name);
CREATE INDEX idx_users_department ON users(department_id);
CREATE INDEX idx_menu_parent ON sys_menu(parent_id);
CREATE INDEX idx_menu_sort ON sys_menu(sort_order);
CREATE INDEX idx_role_code ON role(code);
CREATE INDEX idx_pwd_token ON password_reset_tokens(token);
CREATE INDEX idx_pwd_expires ON password_reset_tokens(expires_at);
