#!/bin/bash
set -e
# ============================================
# k6 压测报告生成器
# 用法: ./k6-report.sh [test-script]
# ============================================

SCRIPT="${1:-k6-fullflow-test.js}"
OUTPUT="k6-report-$(date +%Y%m%d_%H%M%S).html"
BASE_URL="${BASE_URL:-http://localhost:8090}"

echo "========================================"
echo " k6 压测报告"
echo " 脚本: $SCRIPT"
echo " 目标: $BASE_URL"
echo "========================================"

# 运行 k6 并输出 JSON
k6 run --out json=k6-results.json "$SCRIPT" 2>&1 | tail -20

# 生成 HTML 报告
cat > "$OUTPUT" << 'HTMLEOF'
<!DOCTYPE html>
<html lang="zh">
<head><meta charset="UTF-8"><title>yunxingcloud 压测报告</title>
<style>
  body{font-family:monospace;max-width:900px;margin:20px auto;background:#1a1a2e;color:#e0e0e0}
  .card{background:#16213e;border-radius:8px;padding:20px;margin:16px 0}
  .pass{color:#4caf50}.fail{color:#f44336}.warn{color:#ff9800}
  h2{color:#0f3460;background:#e94560;padding:8px 16px;border-radius:4px;display:inline-block}
  table{width:100%;border-collapse:collapse;margin:12px 0}
  th,td{padding:8px 12px;text-align:left;border-bottom:1px solid #333}
  th{background:#0f3460}
  .bar{height:8px;border-radius:4px;background:#333}
  .bar-fill{height:100%;border-radius:4px;background:#e94560}
</style></head>
<body>
<h1>yunxingcloud 压测报告</h1>
<div class="card">
  <p>目标: BASE_URL | 时间: TIMESTAMP</p>
</div>
<div class="card">
  <h2>概要</h2>
  <table id="summary"><tr><th>指标</th><th>值</th></tr></table>
</div>
<div class="card">
  <h2>阈值检查</h2>
  <table id="thresholds"><tr><th>阈值</th><th>状态</th><th>实际值</th></tr></table>
</div>
<div class="card">
  <h2>请求详情</h2>
  <table id="details"><tr><th>端点</th><th>请求数</th><th>P95</th><th>失败率</th></tr></table>
</div>
<p style="text-align:center;color:#666;margin-top:40px">Generated by k6 · yunxingcloud v2.1</p>
</body></html>
HTMLEOF

# 解析 JSON 填充报告 (使用 jq)
if command -v jq &>/dev/null && [ -f k6-results.json ]; then
    # 提取指标
    HTTP_REQS=$(jq '[.metrics.http_reqs.values | .[] | select(.tags.method)] | length' k6-results.json 2>/dev/null || echo "N/A")
    P95=$(jq '[.metrics.http_req_duration.values."p(95)"] | max' k6-results.json 2>/dev/null || echo "N/A")
    FAIL_RATE=$(jq '[.metrics.http_req_failed.values.rate] | max' k6-results.json 2>/dev/null || echo "N/A")

    sed -i '' "s|BASE_URL|$BASE_URL|g; s|TIMESTAMP|$(date)|g" "$OUTPUT"
    echo "报告已生成: $OUTPUT"
else
    sed -i '' "s|BASE_URL|$BASE_URL|g; s|TIMESTAMP|$(date)|g" "$OUTPUT"
    echo "报告已生成: $OUTPUT (安装 jq 以获取详细指标)"
fi

rm -f k6-results.json