apiVersion: v1
kind: ConfigMap
metadata:
  name: yunxingcloud-config
  namespace: yunxingcloud
data:
  NACOS_SERVER: "nacos-service:8848"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DB_USERNAME: "root"
  ES_URIS: "http://elasticsearch-service:9200"
  OTEL_ENABLED: "false"