apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yunxingcloud

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

images:
  - name: yunxingcloud-core
    newTag: latest
  - name: yunxingcloud-usercenter
    newTag: latest
  - name: yunxingcloud-gateway
    newTag: latest
  - name: yunxingcloud-payment
    newTag: latest
  - name: yunxingcloud-order
    newTag: latest
  - name: yunxingcloud-inventory
    newTag: latest