apiVersion: v1
kind: Secret
metadata:
  name: yunxingcloud-secret
  namespace: yunxingcloud
type: Opaque
stringData:
  DB_PASSWORD: "change-me"
  JWT_SECRET: "change-me-at-least-256-bits"
  OAUTH2_CLIENT_SECRET: "change-me"
