apiVersion: v1
kind: Secret
metadata:
  name: yunxingcloud-secrets
  namespace: yunxingcloud
type: Opaque
data:
  DB_PASSWORD: UndhbGY5S3VaNlM2VE1ydGpWenNWYVJ3
  JWT_SECRET: NWlPeFRNaUdCbmJUU3JRQk1lbVlKZmI1cUlCd2lzaDlhWGpSMkVNdmppdjY2Rzd1WnRHOEFkUWRoT1VNUGpiZw==
