apiVersion: v1
kind: Service
metadata:
  name: yunxingcloud-core
  namespace: yunxingcloud
spec:
  selector:
    app: yunxingcloud-core
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yunxingcloud-usercenter
  namespace: yunxingcloud
spec:
  selector:
    app: yunxingcloud-usercenter
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yunxingcloud-gateway
  namespace: yunxingcloud
spec:
  selector:
    app: yunxingcloud-gateway
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yunxingcloud-payment
  namespace: yunxingcloud
spec:
  selector:
    app: yunxingcloud-payment
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yunxingcloud-order
  namespace: yunxingcloud
spec:
  selector:
    app: yunxingcloud-order
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: yunxingcloud-inventory
  namespace: yunxingcloud
spec:
  selector:
    app: yunxingcloud-inventory
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: yunxingcloud
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
