spring:
  config:
    import: ""
  datasource:
    url: jdbc:h2:mem:yunxingcloud_uc;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
    sentinel:
      enabled: false

logging:
  level:
    root: WARN
    com.yunxingcloud: INFO
    org.springframework.security: INFO
