spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          wechat:
            client-id: test
            client-secret: test
          qq:
            client-id: test
            client-secret: test
          alipay:
            client-id: test
            client-secret: test
