spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 1200000
management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    com.yunxingcloud: INFO
    org.springframework.security: WARN
